services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/ideation-system
      - JWT_SECRET=RANDOM_SECRET_561234
      - SALT_ROUND=10
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
